-- MySQL Script generated by MySQL Workbench
-- Qua 06 Nov 2019 17:36:05 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Jorjan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Jorjan` ;

-- -----------------------------------------------------
-- Schema Jorjan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Jorjan` DEFAULT CHARACTER SET utf8 ;
USE `Jorjan` ;

-- -----------------------------------------------------
-- Table `Jorjan`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jorjan`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `state` TINYINT NOT NULL,
  `picture` VARCHAR(255) NULL,
  `avaliation` FLOAT(1) NULL,
  `auth` VARCHAR(500) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Jorjan`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jorjan`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `Jorjan`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jorjan`.`product` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `category` INT NOT NULL,
  `price` FLOAT(3) NOT NULL DEFAULT 0.0,
  `stock` INT(6) NOT NULL DEFAULT 0,
  `owner_id` INT(255) NOT NULL,
  INDEX `fk_product_user1_idx` (`owner_id` ASC),
  PRIMARY KEY (`id`, `category`),
  INDEX `fk_product_category1_idx` (`category` ASC),
  CONSTRAINT `fk_product_user1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `Jorjan`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category`)
    REFERENCES `Jorjan`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Jorjan`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jorjan`.`sales` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `buyer_id` INT(255) NOT NULL,
  `seller_id` INT(255) NOT NULL,
  `observation` VARCHAR(255) NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_user1_idx` (`buyer_id` ASC),
  INDEX `fk_sales_user2_idx` (`seller_id` ASC),
  CONSTRAINT `fk_sales_user1`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `Jorjan`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_user2`
    FOREIGN KEY (`seller_id`)
    REFERENCES `Jorjan`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Jorjan`.`sales_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jorjan`.`sales_has_product` (
  `sales_id` INT(255) NOT NULL,
  `product_id` INT(255) NOT NULL,
  `quantity` INT(3) NOT NULL,
  PRIMARY KEY (`sales_id`, `product_id`),
  INDEX `fk_sales_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_sales_has_product_sales1_idx` (`sales_id` ASC),
  CONSTRAINT `fk_sales_has_product_sales1`
    FOREIGN KEY (`sales_id`)
    REFERENCES `Jorjan`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Jorjan`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
